//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhpaAll.Finance {
    
    
    public partial class AccountHeads {
        
        /// <summary>
        /// ctlHelpfulInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Accordion ctlHelpfulInfo;
        
        /// <summary>
        /// JPanel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.JPanel JPanel1;
        
        /// <summary>
        /// Menu2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Menu Menu2;
        
        /// <summary>
        /// dsAccountTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Eclipse.PhpaLibrary.Web.PhpaLinqDataSource dsAccountTypes;
        
        /// <summary>
        /// ddlAccountTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.DropDownListEx ddlAccountTypes;
        
        /// <summary>
        /// btnMark control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.ButtonEx btnMark;
        
        /// <summary>
        /// btnClearMark control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.ButtonEx btnClearMark;
        
        /// <summary>
        /// btnExpand control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.ButtonEx btnExpand;
        
        /// <summary>
        /// btnCollapse control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.ButtonEx btnCollapse;
        
        /// <summary>
        /// btnNewTop control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.LinkButtonEx btnNewTop;
        
        /// <summary>
        /// dsHeads control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Eclipse.PhpaLibrary.Web.Specialized.HeadsHierarchicalDataSourceControl dsHeads;
        
        /// <summary>
        /// ctlEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PhpaAll.HeadOfAccountEditor ctlEditor;
        
        /// <summary>
        /// tvHeads control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TreeView tvHeads;
    }
}
