//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Finance {
    
    
    public partial class VoucherSearch {
        
        /// <summary>
        /// HyperLink2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink HyperLink2;
        
        /// <summary>
        /// PrinterFriendlyButton1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Finance.Controls.PrinterFriendlyButton PrinterFriendlyButton1;
        
        /// <summary>
        /// panelFilters control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.JPanel panelFilters;
        
        /// <summary>
        /// TwoColumnPanel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.UI.TwoColumnPanel TwoColumnPanel1;
        
        /// <summary>
        /// LeftLabel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.UI.LeftLabel LeftLabel1;
        
        /// <summary>
        /// tbParticulars control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.TextBoxEx tbParticulars;
        
        /// <summary>
        /// LeftLabel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.UI.LeftLabel LeftLabel2;
        
        /// <summary>
        /// tbPayeeName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.TextBoxEx tbPayeeName;
        
        /// <summary>
        /// LeftLabel3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.UI.LeftLabel LeftLabel3;
        
        /// <summary>
        /// tbVoucherCode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.TextBoxEx tbVoucherCode;
        
        /// <summary>
        /// LeftLabel4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.UI.LeftLabel LeftLabel4;
        
        /// <summary>
        /// tbFromDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.TextBoxEx tbFromDate;
        
        /// <summary>
        /// tbToDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.TextBoxEx tbToDate;
        
        /// <summary>
        /// LeftLabel5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.UI.LeftLabel LeftLabel5;
        
        /// <summary>
        /// tbEmployee control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.AutoComplete tbEmployee;
        
        /// <summary>
        /// LeftLabel6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.UI.LeftLabel LeftLabel6;
        
        /// <summary>
        /// tbContractor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.AutoComplete tbContractor;
        
        /// <summary>
        /// chkJobSpecified control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.CheckBoxEx chkJobSpecified;
        
        /// <summary>
        /// LeftLabel7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.UI.LeftLabel LeftLabel7;
        
        /// <summary>
        /// tbHeadOfAccount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.AutoComplete tbHeadOfAccount;
        
        /// <summary>
        /// LeftLabel8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.UI.LeftLabel LeftLabel8;
        
        /// <summary>
        /// tbDateCreated control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.TextBoxEx tbDateCreated;
        
        /// <summary>
        /// dsAccountTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Eclipse.PhpaLibrary.Web.PhpaLinqDataSource dsAccountTypes;
        
        /// <summary>
        /// cblAccountTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.CheckBoxListEx cblAccountTypes;
        
        /// <summary>
        /// btnClear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.ButtonEx btnClear;
        
        /// <summary>
        /// lbldiffrence control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbldiffrence;
        
        /// <summary>
        /// dsVoucherDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Eclipse.PhpaLibrary.Web.PhpaLinqDataSource dsVoucherDetails;
        
        /// <summary>
        /// gvSearchVoucher control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.GridViewEx gvSearchVoucher;
    }
}
