//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Controls {
    
    
    public partial class EmployeeAdjustmentEditor {
        
        /// <summary>
        /// dsEditEmpAdjustments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Eclipse.PhpaLibrary.Web.PhpaLinqDataSource dsEditEmpAdjustments;
        
        /// <summary>
        /// btnNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.LinkButtonEx btnNew;
        
        /// <summary>
        /// valSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.ValidationSummary valSummary;
        
        /// <summary>
        /// hdemployeeid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdemployeeid;
        
        /// <summary>
        /// gvEditEmpAdjustments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.GridViewExInsert gvEditEmpAdjustments;
    }
}
