<?xml version="1.0" encoding="utf-8"?><Database Name="PHPA2151114" Class="PhpaBillsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=w12obama;Initial Catalog=PHPA2151114;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PHPA2151114ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Bill" Member="Bills">
    <Type Name="Bill">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BillNumber" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="BillDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="DueDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="SubmittedToDivision" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="PaidDate" Storage="_PaidOn" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="SubmittedToDivisionId" Storage="_DivisionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContractorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ApprovedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ApprovedOn" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BillImage" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>