<?xml version="1.0" encoding="utf-8"?><Database Name="PHPADEV" Class="PhpaBillsDataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=w12obama;Initial Catalog=PHPADEV;Persist Security Info=True;User ID=sa;MultipleActiveResultSets=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="default" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Division" Member="Divisions" AccessModifier="Internal">
    <Type Name="Division" AccessModifier="Internal">
      <Column Name="DivisionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsReadOnly="true" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DivisionCode" Type="System.String" DbType="NVarChar(25) NOT NULL" IsReadOnly="true" CanBeNull="false" />
      <Column Name="DivisionGroup" Type="System.String" DbType="NVarChar(30) NOT NULL" IsReadOnly="true" CanBeNull="false" />
      <Column Name="DivisionName" Type="System.String" DbType="NVarChar(80) NOT NULL" IsReadOnly="true" CanBeNull="false" />
      <Association Name="Division_Bill" Member="Bills" ThisKey="DivisionId" OtherKey="DivisionId" Type="Bill" />
      <Association Name="Division_Bill1" Member="Bills1" ThisKey="DivisionId" OtherKey="AtDivisionId" Type="Bill" />
    </Type>
  </Table>
  <Table Name="dbo.Contractor" Member="Contractors" AccessModifier="Internal">
    <Type Name="Contractor" AccessModifier="Internal">
      <Column Name="ContractorId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsReadOnly="true" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContractorName" Type="System.String" DbType="NVarChar(120) NOT NULL" IsReadOnly="true" CanBeNull="false" />
      <Column Name="ContractorCode" Type="System.String" DbType="NVarChar(20) NOT NULL" IsReadOnly="true" CanBeNull="false" />
      <Column Name="Nationality" Type="System.String" DbType="NVarChar(2) NOT NULL" IsReadOnly="true" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250)" IsReadOnly="true" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(25)" IsReadOnly="true" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(30)" IsReadOnly="true" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(25)" IsReadOnly="true" CanBeNull="true" />
      <Column Name="Postal_Code" Type="System.String" DbType="NVarChar(10)" IsReadOnly="true" CanBeNull="true" />
      <Column Name="Contact_person" Type="System.String" DbType="NVarChar(50)" IsReadOnly="true" CanBeNull="true" />
      <Column Name="Phone1" Type="System.String" DbType="NVarChar(25)" IsReadOnly="true" CanBeNull="true" />
      <Column Name="Phone2" Type="System.String" DbType="NVarChar(25)" IsReadOnly="true" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(25)" IsReadOnly="true" CanBeNull="true" />
      <Association Name="Contractor_Bill" Member="Bills" ThisKey="ContractorId" OtherKey="ContractorId" Type="Bill" />
    </Type>
  </Table>
  <Table Name="dbo.Bill" Member="Bills" AccessModifier="Internal">
    <Type Name="Bill" AccessModifier="Internal">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BillNumber" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="BillDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="DueDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="ReceiviedDate" Member="ReceivedDate" Storage="_SubmittedOnDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="DivisionId" Storage="_SubmitedToDivisionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContractorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ApprovedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ApprovedOn" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Version" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="Created" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Modified" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Particulars" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="StationId" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="AtDivisionId" Storage="_CurrentDivisionId" Type="System.Int32" CanBeNull="true" />
      <Association Name="Bill_BillImage" Member="BillImages" ThisKey="Id" OtherKey="BillId" Type="BillImage" />
      <Association Name="Bill_Voucher" Member="Voucher" Storage="_Vouchers" ThisKey="Id" OtherKey="BillId" Type="Voucher" Cardinality="One" />
      <Association Name="Contractor_Bill" Member="Contractor" ThisKey="ContractorId" OtherKey="ContractorId" Type="Contractor" IsForeignKey="true" />
      <Association Name="Division_Bill" Member="Division" ThisKey="DivisionId" OtherKey="DivisionId" Type="Division" IsForeignKey="true" />
      <Association Name="Station_Bill" Member="Station" ThisKey="StationId" OtherKey="StationId" Type="Station" IsForeignKey="true" />
      <Association Name="Division_Bill1" Member="AtDivision" Storage="_CurrentDivision" ThisKey="AtDivisionId" OtherKey="DivisionId" Type="Division" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="PIS.Station" Member="Stations" AccessModifier="Internal">
    <Type Name="Station" AccessModifier="Internal">
      <Column Name="StationId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StationName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedWorkstation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Modified" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifiedWorkstation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Version" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Association Name="Station_Bill" Member="Bills" ThisKey="StationId" OtherKey="StationId" Type="Bill" />
    </Type>
  </Table>
  <Table Name="dbo.BillImage" Member="BillImages" AccessModifier="Internal">
    <Type Name="BillImage" AccessModifier="Internal">
      <Column Name="id" Member="Id" Storage="_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="BillId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="BillImageData" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ImageContentType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FileName" Type="System.String" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ContentLength" Type="System.String" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Bill_BillImage" Member="Bill" ThisKey="BillId" OtherKey="Id" Type="Bill" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Voucher" Member="Vouchers" AccessModifier="Internal">
    <Type Name="Voucher" AccessModifier="Internal">
      <Column Name="VoucherId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VoucherType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VoucherDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="VoucherCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DivisionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CheckNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayeeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Particulars" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Voucher_last_edited_by_o" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="CreatedWorkstation" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Modified" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ModifiedWorkstation" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Version" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="IsChequeReconcile" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="StationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BillId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Bill_Voucher" Member="Bill" ThisKey="BillId" OtherKey="Id" Type="Bill" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BillAudit2" Member="BillAudit2s" AccessModifier="Internal">
    <Type Name="BillAudit2" AccessModifier="Internal">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BillId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Association Name="BillAudit2_BillAuditDetail" Member="BillAuditDetails" ThisKey="Id" OtherKey="BillAuditId" Type="BillAuditDetail" />
    </Type>
  </Table>
  <Table Name="dbo.BillAuditDetail" Member="BillAuditDetails" AccessModifier="Internal">
    <Type Name="BillAuditDetail" AccessModifier="Internal">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BillAuditId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FieldName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="OldValue" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NewValue" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="BillAudit2_BillAuditDetail" Member="BillAudit2" ThisKey="BillAuditId" OtherKey="Id" Type="BillAudit2" IsForeignKey="true" />
    </Type>
  </Table>
</Database>