//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.MIS {
    
    
    public partial class FinancialProgress {
        
        /// <summary>
        /// pfb control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Finance.Controls.PrinterFriendlyButton pfb;
        
        /// <summary>
        /// sp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.StatusPanel sp;
        
        /// <summary>
        /// tcp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.UI.TwoColumnPanel tcp;
        
        /// <summary>
        /// dsProgressFormat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Eclipse.PhpaLibrary.Web.PhpaLinqDataSource dsProgressFormat;
        
        /// <summary>
        /// ddlProgressformat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.DropDownListEx ddlProgressformat;
        
        /// <summary>
        /// ddlProgressDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.DropDownSuggest ddlProgressDate;
        
        /// <summary>
        /// lblStartsWith control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.UI.LeftLabel lblStartsWith;
        
        /// <summary>
        /// tbStartsWith control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.TextBoxEx tbStartsWith;
        
        /// <summary>
        /// btnGo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.ButtonEx btnGo;
        
        /// <summary>
        /// hlDataEntry control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink hlDataEntry;
        
        /// <summary>
        /// btnSave1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.ButtonEx btnSave1;
        
        /// <summary>
        /// ValidationSummary1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.ValidationSummary ValidationSummary1;
        
        /// <summary>
        /// ds control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Eclipse.PhpaLibrary.Web.PhpaLinqDataSource ds;
        
        /// <summary>
        /// gv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.GridViewEx gv;
        
        /// <summary>
        /// btnSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.ButtonEx btnSave;
        
        /// <summary>
        /// hfDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfDate;
        
        /// <summary>
        /// hfProgressformat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfProgressformat;
        
        /// <summary>
        /// dlgActivity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Dialog dlgActivity;
    }
}
