//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhpaAll.Reports {
    
    
    public partial class TrialBalance {
        
        /// <summary>
        /// HyperLink2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink HyperLink2;
        
        /// <summary>
        /// PrinterFriendlyButton1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PhpaAll.Controls.PrinterFriendlyButton PrinterFriendlyButton1;
        
        /// <summary>
        /// dsVoucherDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Eclipse.PhpaLibrary.Web.PhpaLinqDataSource dsVoucherDetails;
        
        /// <summary>
        /// tbMonth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.TextBoxEx tbMonth;
        
        /// <summary>
        /// btnShowReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.ButtonEx btnShowReport;
        
        /// <summary>
        /// ExportBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.ButtonEx ExportBtn;
        
        /// <summary>
        /// vsMonth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.Input.ValidationSummary vsMonth;
        
        /// <summary>
        /// gvTrialBalance control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EclipseLibrary.Web.JQuery.GridViewEx gvTrialBalance;
    }
}
